### ISSUE TITLE
Devidend smaler than devisor always equals 0?

### ISSUE THREAD

**Issue by MrFibunacci** [Mariotti94/BigFloat#1]
Hey, 
I use your library for an projet of mine where I [aproximate the value of pi](https://github.com/MrFibunacci/approximate-pi).
My idea was it to get due your lib an higher percision.
But it seems like it doesnt calculate at all:

My calculation is `a/b` where `a` is smaler than `b` and it always returns me 0. I have went throu your code but dont quite understand why.

the code:
```c++
BigFloat a = std::to_string(inCircle);
BigFloat b = std::to_string(total);
	
BigFloat result = (a / b) * 4;
```

the wanted values are in `a` and `b` so there is no error. The issue seems to be in the calculation as `result` is always 0.

**Comment by Mariotti94** [comment]
@MrFibunacci 
With division, in this library, the result has the same amount of decimals as the dividend.
So, if you have a dividend with zero decimal points, the result will have zero decimal points. 
To avoid this, you can change the precision of the dividend before dividing, or you can use the precision division function that lets you set the number of decimals you want to have in the result, i'd recommend the second option.
Here are examples:
```
//This sets a to have 10 decimal points
a.SetPrecision(10);

//This executes a division with result having 10 decimal points
BigFloat result = BigFloat::PrecDiv(a,b,10);
```

**Comment by MrFibunacci** [comment]
@Mariotti94 
Thanks a lot. That helped.
